name: Dependency Check

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  dependency-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install pip-audit
          pip-audit

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: |
          cd frontend
          npm install
          npm audit